# Importing numpy

In [40]:
# import numpy
import numpy as np

# check the version of the numpy package
print('numpy:', np.__version__)

# Checking the available methods
print(dir(np))


numpy: 1.26.2
['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_i

# Creating numpy array

In [41]:
import numpy as np

# Creating a python List
python_list = [1, 2, 3, 4, 5]

# Checking data types
# print('Type:', type(python_list))

print(python_list)

two_dimensional_list = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

print(two_dimensional_list)  # Fixed the extra square bracket in this line

# Creating a NumPy (Numerical Python) array from the python list
numpy_array_from_list = np.array(python_list)

print(type(numpy_array_from_list))
print(numpy_array_from_list)


[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [34]:
# creating  int numpy arrays
# Creating python List
python_list = [1,2,3,4,5]

# Checking data types
# print('Type:', type (python_list)) 
    
print(python_list) 

two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]

print(two_dimensional_list)  ]

# Creating Numpy(Numerical Python) array from python list

numpy_array_from_list = np.array(python_list)
print(type (numpy_array_from_list))   
print(numpy_array_from_list) 

SyntaxError: unmatched ']' (2149691960.py, line 12)

# Creating float numpy arrays

In [42]:
# Python list
python_list = [1, 2, 3, 4, 5]

numy_array_from_list2 = np.array(python_list, dtype=float)
print(numy_array_from_list2)  # array([1., 2., 3., 4., 5.])


[1. 2. 3. 4. 5.]


# Creating boolean numpy arrays

In [43]:
numpy_bool_array = np.array([0, 1, -1, 0, 0], dtype=bool)
print(numpy_bool_array) # array([False,  True,  True, False, False])

[False  True  True False False]


# Creating multidimensional array using numpy

In [44]:
two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
numpy_two_dimensional_list = np.array(two_dimensional_list)
print(type (numpy_two_dimensional_list))
print(numpy_two_dimensional_list)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Converting numpy array to list

In [45]:
# convert an array back to a python list using tolist().
np_to_list = numpy_array_from_list.tolist()
print(type (np_to_list))
print('one dimensional array:', np_to_list)
print('two dimensional array: ', numpy_two_dimensional_list.tolist())

<class 'list'>
one dimensional array: [1, 2, 3, 4, 5]
two dimensional array:  [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


# Creating numpy array from tuple 

In [46]:
# Numpy array from tuple
# Creating tuple in Python
python_tuple = (1,2,3,4,5)
print(type (python_tuple)) 
print('python_tuple: ', python_tuple) 

numpy_array_from_tuple = np.array(python_tuple)
print(type (numpy_array_from_tuple)) 
print('numpy_array_from_tuple: ', numpy_array_from_tuple) 

<class 'tuple'>
python_tuple:  (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
numpy_array_from_tuple:  [1 2 3 4 5]


# Shape of numpy array

In [47]:
nums = np.array([1, 2, 3, 4, 5])
print(nums)
print('shape of nums: ', nums.shape)
print(numpy_two_dimensional_list)
print('shape of numpy_two_dimensional_list: ', numpy_two_dimensional_list.shape)
three_by_four_array = np.array([[0, 1, 2, 3],
[4,5,6,7],
[8,9,10, 11]])
print(three_by_four_array.shape)

[1 2 3 4 5]
shape of nums:  (5,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape of numpy_two_dimensional_list:  (3, 3)
(3, 4)


# Data type of numpy array

In [48]:
int_lists = [-3, -2, -1, 0, 1, 2,3]
int_array = np.array(int_lists)
float_array = np.array(int_lists, dtype=float)

print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)

[-3 -2 -1  0  1  2  3]
int32
[-3. -2. -1.  0.  1.  2.  3.]
float64


# Size of a numpy array

In [49]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
two_dimensional_list = np.array([[0, 1, 2],
                              [3, 4, 5],
                              [6, 7, 8]])

print('The size:', numpy_array_from_list.size) # 5
print('The size:', two_dimensional_list.size)  # 3

The size: 5
The size: 9


# Mathematical Operation using numpy

# Addititon

In [50]:
# Addition
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_plus_original = numpy_array_from_list  + 10
print(ten_plus_original)

original array:  [1 2 3 4 5]
[11 12 13 14 15]


# Substration

In [51]:
# Subtraction
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_minus_original = numpy_array_from_list  - 10
print(ten_minus_original)

original array:  [1 2 3 4 5]
[-9 -8 -7 -6 -5]


# Multiplication

In [52]:
# Multiplication
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list * 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[10 20 30 40 50]


# Division

In [53]:
# Division
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list / 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[0.1 0.2 0.3 0.4 0.5]


# Modulus

In [54]:
# Modulus; Finding the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list % 3
print(ten_times_original)

original array:  [1 2 3 4 5]
[1 2 0 1 2]


# Floor Division 

In [55]:
# Floor division: the division result without the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list // 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[0 0 0 0 0]


# Exponential

In [56]:
# Exponential is finding some number the power of another
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list  ** 2
print(ten_times_original)

original array:  [1 2 3 4 5]
[ 1  4  9 16 25]


# Checking Data types

In [57]:
#Int,  Float numbers
numpy_int_arr = np.array([1,2,3,4])
numpy_float_arr = np.array([1.1, 2.0,3.2])
numpy_bool_arr = np.array([-3, -2, 0, 1,2,3], dtype='bool')

print(numpy_int_arr.dtype)
print(numpy_float_arr.dtype)
print(numpy_bool_arr.dtype)

int32
float64
bool


# Converting types 

In [58]:
# int to float
numpy_int_arr = np.array([1,2,3,4], dtype = 'float')
numpy_int_arr

array([1., 2., 3., 4.])

In [59]:
# float to int 
numpy_int_arr = np.array([1., 2., 3., 4.], dtype = 'int')
numpy_int_arr

array([1, 2, 3, 4])

In [60]:
# int to boolean
np.array([-3, -2, 0, 1,2,3], dtype='bool')

array([ True,  True, False,  True,  True,  True])

In [61]:

# Python list
python_list = [1, 2, 3, 4, 5]

# Create a NumPy array from the list
numy_array_from_list2 = np.array(python_list, dtype=float)

# Convert the array to integer and then to string
result_array = numy_array_from_list2.astype('int').astype('str')

# Output
print(result_array)


['1' '2' '3' '4' '5']


# Multi-dimensional arrays

In [62]:
# 2 Dimension Array
two_dimension_array = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(type (two_dimension_array))
print(two_dimension_array)
print('Shape: ', two_dimension_array.shape)
print('Size:', two_dimension_array.size)
print('Data type:', two_dimension_array.dtype)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Size: 9
Data type: int32


# Getting items from numpy 

In [63]:
# 2 Dimension Array
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dimension_array[0]
second_row = two_dimension_array[1]
third_row = two_dimension_array[2]
print('First row:', first_row)
print('Second row:', second_row)
print('Third row: ', third_row)

First row: [1 2 3]
Second row: [4 5 6]
Third row:  [7 8 9]


In [64]:
first_column= two_dimension_array[:,0]
second_column = two_dimension_array[:,1]
third_column = two_dimension_array[:,2]
print('First column:', first_column)
print('Second column:', second_column)
print('Third column: ', third_column)
print(two_dimension_array)

First column: [1 4 7]
Second column: [2 5 8]
Third column:  [3 6 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Slicing numpy array

In [65]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_two_rows_and_columns = two_dimension_array[0:2, 0:2]
print(first_two_rows_and_columns)

[[1 2]
 [4 5]]


# Reverse the rows and the whole array

In [66]:
two_dimension_array[::]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Represent missing values

In [67]:
print(two_dimension_array)
two_dimension_array[1,1] = 55
two_dimension_array[1,2] =44
print(two_dimension_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 55 44]
 [ 7  8  9]]


In [68]:
# Numpy Zeroes
# numpy.zeros(shape, dtype=float, order='C')
numpy_zeroes = np.zeros((3,3),dtype=int,order='C')
numpy_zeroes

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [69]:
# Numpy Zeroes
numpy_ones = np.ones((3,3),dtype=int,order='C')
print(numpy_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [70]:
twoes = numpy_ones * 2
twoes

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [71]:
# Reshape
# numpy.reshape(), numpy.flatten()
first_shape  = np.array([(1,2,3), (4,5,6)])
print(first_shape)
reshaped = first_shape.reshape(3,2)
print(reshaped)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [72]:
flattened = reshaped.flatten()
flattened

array([1, 2, 3, 4, 5, 6])

In [73]:
## Horitzontal Stack
np_list_one = np.array([1,2,3])
np_list_two = np.array([4,5,6])
print(np_list_one + np_list_two)

print('Horizontal Append:', np.hstack((np_list_one, np_list_two)))

[5 7 9]
Horizontal Append: [1 2 3 4 5 6]


In [74]:
## Vertical Stack
print('Vertical Append:', np.vstack((np_list_one, np_list_two)))

Vertical Append: [[1 2 3]
 [4 5 6]]


# Generating Random Numbers 

In [75]:
# Generate a random float  number
random_float = np.random.random()
random_float

0.6036237498531668

In [76]:
# Generate a random float  number
random_floats = np.random.random(5)
random_floats

array([0.19186929, 0.21171261, 0.72904482, 0.69570237, 0.90430036])

In [77]:
# Generating a random integers between 0 and 10
random_int = np.random.randint(0, 11)
random_int

10

In [78]:
# Generating a random integers between 2 and 11, and creating a one row array
random_int = np.random.randint(2,10, size=4)
random_int

array([3, 4, 2, 2])

In [79]:
# Generating a random integers between 0 and 10
random_int = np.random.randint(2,10, size=(3,3))
random_int

array([[3, 2, 4],
       [8, 5, 6],
       [6, 9, 3]])

In [80]:
# np.random.normal(mu, sigma, size)
normal_array = np.random.normal(79, 15, 80)
normal_array

array([ 87.98817319,  85.88559155,  63.43442942,  74.38572692,
        82.26832487,  86.16718211, 107.59354946,  98.05486099,
        63.79052386,  87.91812645,  87.20101002, 101.11403104,
        89.96346001,  89.90022536,  85.64649689,  76.76607349,
        75.43701713,  70.41371327,  90.24256753,  79.23230538,
        75.94925383,  77.4879038 ,  87.10189557,  90.60726651,
        92.01131831, 104.31203173,  83.82574213,  69.40089552,
        81.73467045,  75.92074416,  85.19100941,  63.32281552,
        46.57362136,  79.83545779,  97.4001535 , 104.9697343 ,
        86.78322378,  75.53061413,  54.40165574,  87.17308496,
        81.05424244,  38.96466092, 120.68980404,  76.82041575,
        66.22407198,  76.49645874,  76.06216078,  80.89906604,
       103.31363455,  90.07405913,  96.86908202,  77.72334454,
        79.35034796,  57.45696264,  94.86336444,  69.53022601,
        93.40303364,  75.33879436,  75.34476941,  90.2001103 ,
        78.70669598,  62.58268101,  44.35798355, 101.44

# Numpy and Statistics 

In [81]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
plt.hist(normal_array, color="grey", bins=50)

(array([1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 3., 0., 0., 3., 1., 1.,
        0., 2., 2., 1., 2., 8., 5., 3., 4., 3., 3., 4., 6., 0., 6., 2., 3.,
        1., 2., 1., 0., 2., 3., 1., 2., 0., 0., 0., 0., 0., 0., 0., 1.]),
 array([ 38.96466092,  40.59916379,  42.23366665,  43.86816951,
         45.50267237,  47.13717524,  48.7716781 ,  50.40618096,
         52.04068382,  53.67518668,  55.30968955,  56.94419241,
         58.57869527,  60.21319813,  61.847701  ,  63.48220386,
         65.11670672,  66.75120958,  68.38571245,  70.02021531,
         71.65471817,  73.28922103,  74.92372389,  76.55822676,
         78.19272962,  79.82723248,  81.46173534,  83.09623821,
         84.73074107,  86.36524393,  87.99974679,  89.63424966,
         91.26875252,  92.90325538,  94.53775824,  96.1722611 ,
         97.80676397,  99.44126683, 101.07576969, 102.71027255,
        104.34477542, 105.97927828, 107.61378114, 109.248284  ,
        110.88278687, 112.51728973, 114.15179259, 115.78629545,
      

# matrix in numpy 

In [82]:
four_by_four_matrix = np.matrix(np.ones((4,4), dtype=float))
four_by_four_matrix

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [83]:
np.asarray(four_by_four_matrix)[2] = 2
four_by_four_matrix

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [1., 1., 1., 1.]])

# Numpy numpy.arrange()

In [84]:
# creating list using range(starting, stop, step)
lst = range(0, 11, 2)
lst

range(0, 11, 2)

In [85]:
for l in lst:
    print(l)

0
2
4
6
8
10


In [86]:
# Similar to range arange numpy.arange(start, stop, step)
whole_numbers = np.arange(0, 20, 1)
whole_numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [87]:
natural_numbers = np.arange(1, 20, 1)
natural_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [88]:
odd_numbers = np.arange(1, 20, 2)
odd_numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [89]:
even_numbers = np.arange(2, 20, 2)
even_numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

# Creating sequence of numbers using linspace 

In [90]:
# numpy.linspace()
# numpy.logspace() in Python with Example
# For instance, it can be used to create 10 values from 1 to 5 evenly spaced.
np.linspace(1.0, 5.0, num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [91]:
# not to include the last value in the interval
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [92]:
# LogSpace
# LogSpace returns even spaced numbers on a log scale. Logspace has the same parameters as np.linspace.

# Syntax:

# numpy.logspace(start, stop, num, endpoint)

np.logspace(2, 4.0, num=4)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [93]:
# to check the size of an array
x = np.array([1,2,3], dtype=np.complex128)
x

array([1.+0.j, 2.+0.j, 3.+0.j])

In [94]:
x.itemsize

16

In [95]:
# indexing and Slicing NumPy Arrays in Python
np_list = np.array([(1,2,3), (4,5,6)])
np_list

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
print('First row: ', np_list[0])
print('Second row: ', np_list[1])

First row:  [1 2 3]
Second row:  [4 5 6]


In [97]:
print('First column: ', np_list[:,0])
print('Second column: ', np_list[:,1])
print('Third column: ', np_list[:,2])

First column:  [1 4]
Second column:  [2 5]
Third column:  [3 6]


# Numpy Statistcal Functions with Example

In [98]:
np_normal_dis = np.random.normal(5, 0.5, 100)
np_normal_dis
## min, max, mean, median, sd
print('min: ', two_dimension_array.min())
print('max: ', two_dimension_array.max())
print('mean: ',two_dimension_array.mean())
# print('median: ', two_dimension_array.median())
print('sd: ', two_dimension_array.std())

min:  1
max:  55
mean:  14.777777777777779
sd:  18.913709183069525


In [99]:
print(two_dimension_array)
print('Column with minimum: ', np.amin(two_dimension_array,axis=0))
print('Column with maximum: ', np.amax(two_dimension_array,axis=0))
print('=== Row ==')
print('Row with minimum: ', np.amin(two_dimension_array,axis=1))
print('Row with maximum: ', np.amax(two_dimension_array,axis=1))

[[ 1  2  3]
 [ 4 55 44]
 [ 7  8  9]]
Column with minimum:  [1 2 3]
Column with maximum:  [ 7 55 44]
=== Row ==
Row with minimum:  [1 4 7]
Row with maximum:  [ 3 55  9]


# Repeating sequences

In [100]:
a = [1,2,3]

# Repeat whole of 'a' two times
print('Tile:   ', np.tile(a, 2))

# Repeat each element of 'a' two times
print('Repeat: ', np.repeat(a, 2))

Tile:    [1 2 3 1 2 3]
Repeat:  [1 1 2 2 3 3]


# generate random numbers 

In [101]:
# One random number between [0,1)
one_random_num = np.random.random()
one_random_in = np.random
print(one_random_num)

0.5647492320301276


In [102]:
# Random numbers between [0,1) of shape 2,3
r = np.random.random(size=[2,3])
print(r)

[[0.07370352 0.71416289 0.35823625]
 [0.44599272 0.66115415 0.27275848]]


In [103]:
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))

['u' 'a' 'o' 'a' 'e' 'e' 'o' 'i' 'a' 'o']


In [104]:
# Random numbers between [0, 1] of shape 2, 2
rand = np.random.rand(2,2)
rand

array([[0.74985529, 0.15059607],
       [0.65762854, 0.79189316]])

In [105]:
rand2 = np.random.randn(2,2)
rand2

array([[-1.38059932,  0.40481159],
       [ 0.98011359,  1.27656852]])

In [106]:
# Random integers between [0, 10) of shape 2,5
rand_int = np.random.randint(0, 10, size=[5,3])
rand_int

array([[7, 1, 3],
       [5, 8, 2],
       [7, 3, 9],
       [0, 4, 3],
       [9, 6, 2]])

In [107]:
from scipy import stats
np_normal_dis = np.random.normal(5, 0.5, 1000) # mean, standard deviation, number of samples
np_normal_dis
## min, max, mean, median, sd
print('min: ', np.min(np_normal_dis))
print('max: ', np.max(np_normal_dis))
print('mean: ', np.mean(np_normal_dis))
print('median: ', np.median(np_normal_dis))
print('mode: ', stats.mode(np_normal_dis))
print('sd: ', np.std(np_normal_dis))

min:  3.251939959610382
max:  6.57292854084
mean:  5.00825208364028
median:  5.011823308748982
mode:  ModeResult(mode=3.251939959610382, count=1)
sd:  0.48181141689240436


In [108]:
plt.hist(np_normal_dis, color="grey", bins=21)
plt.show()

# Linear Algebra

In [109]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2,3])
g = np.array([4,5,3])
### 1*4+2*5 + 3*6
np.dot(f, g)  

23

# Numpy matrix multiplication with np.matmul()

In [110]:
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]]
i = [[5,6],[7,8]]
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

In [111]:
np.linalg.det(i)

-1.999999999999999

In [113]:
Z = np.zeros((8,8))
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [114]:
new_list = [ x + 2 for x in range(0, 11)]
new_list

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [116]:
np_arr = np.array(range(0, 11))
np_arr_add = np_arr + 2
np_arr_add



array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [117]:
temp = np.array([1,2,3,4,5])
pressure = temp * 2 + 5
pressure

array([ 7,  9, 11, 13, 15])

In [118]:
plt.plot(temp,pressure)
plt.xlabel('Temperature in oC')
plt.ylabel('Pressure in atm')
plt.title('Temperature vs Pressure')
plt.xticks(np.arange(0, 6, step=0.5))
plt.show()

In [120]:
mu = 28
sigma = 15
samples = 100000

x = np.random.normal(mu, sigma, samples)

# Use displot instead of distplot
sns.displot(x, kde=True)

# Set labels
plt.xlabel("x")
plt.ylabel("y")

# Show the plot
plt.show()
